[{"tile": "AZ_CochiseCounty_2_2020", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/AZ_CochiseCounty_2_2020/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "AZ_FEMA_Central_2017", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/AZ_FEMA_Central_2017/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "CA_FEMAR9Fresno_1_2019", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "FL_PascoCo_2011", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "FL_WaltonCo_2006", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "KS_Statewide_B4_2018", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/KS_Statewide_B4_2018/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "LA_CPRA_B2_2019", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "MN_RockCo_2010", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/MN_RockCo_2010/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "MN_WasecaCo_2010", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/MN_WasecaCo_2010/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "NC_NashCo_2014", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/NC_NashCo_2014/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "SC_GreenwoodCo_2008", "error": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"}, {"tile": "SD_Grant_County_2012", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/SD_Grant_County_2012/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"tile": "TN_ShelbyCo_2012", "error": "HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /usgs-lidar-public/TN_ShelbyCo_2012/ept.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"}, {"error": "Could not create geometry because of errors while reading input."}, {"error": "Could not create geometry because of errors while reading input."}, {"tile": "USGS_LPC_WA_Western_North_2016_LAS_2018", "error": "Expecting value: line 1 column 1 (char 0)"}, {"tile": "USGS_LPC_WA_Western_South_2016_LAS_2018", "error": "Expecting value: line 1 column 1 (char 0)"}, {"args": ["pdal", "info", "--all", "--driver", "readers.ept", "--readers.ept.resolution=800.0", "--readers.ept.threads=6", "--filters.hexbin.edge_size=1000", "--filters.hexbin.threshold=1", "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_Oshkosh_3Rivers_FondDuLac_TL_2018/ept.json"], "error": "PDAL: readers.ept: Error reading tile: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/WI_Oshkosh_3Rivers_FondDuLac_TL_2018/ept-data/0-0-0-0.laz\n\n"}]